name: weather
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  dio: ^4.0.4
  logger: ^1.1.0
  freezed: ^1.1.1
  equatable: ^2.0.3
  velocity_x: ^3.3.0
  auto_route: ^3.2.2
  flutter_gen: ^4.1.5
  fluttericon: 2.0.0
  flutter_hooks: ^0.18.2
  hooks_riverpod: ^1.0.3
  touchable_opacity: 1.2.0
  freezed_annotation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.7
  flutter_lints: ^1.0.0
  auto_route_generator: ^3.2.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/co_rain.png
    - assets/images/humidity.png
    - assets/images/wind.png